FROM node:alpine
RUN npm install -g pnpm
WORKDIR /app

COPY package.json pnpm-lock.yaml  pnpm-workspace.yaml turbo.json /app/

COPY packages ./packages
COPY ./apps/frontend ./apps/frontend

RUN pnpm i

WORKDIR /app/packages/db
RUN command pwd && ls -la
RUN npx prisma generate

WORKDIR /app/apps/frontend

ARG NEXTAUTH_URL
ARG NEXTAUTH_SECRET
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_API_URL_V1
ARG NEXT_PUBLIC_WS_URL


WORKDIR /app/apps/frontend
RUN pnpm build

EXPOSE 3000

CMD [ "pnpm","dev" ]